appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  linux_aarch64: default
  linux_ppc64le: azure
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: I/TOER+kjoi+5AUBSCC6I0Fe+JdAxw0KQRO71yWtho40VjFdUr5/frqzyq5L7C9CHUNHAtjZQBJVfq2qCawjsg1VzHH0aRBPENJKQ8vNQLM3KqGHEpzFk8V5IcCqAnIERVroKkfKeh71by8Fsfn8yeF9n1CzQtthrOF9RqjjoLbyPh30EF/+TN5hOswmz6oLBNU7loLOaYx1Hq/j+P0bFAVfuS+pTSvlsYXN/vxBGYKu8EgmczTQdijMMOh91JVMtde6S0vfl+PZzYtKY8k2ibCpdPfyBsXkTZfn3pN0F1/dzWbSZlVkEUTVDPvjv57WECPSrDmeALa4hJmjO2IE2qusvp74SmzDvU+NSIvIIXgJXeUFZnD92+1aVHATCRoLRcH6jh52tj6T2Thuxt9+0of8MCHBR8dSWb+P/ohFWD7DKGTqukzdc3OmjF8ABG4upyYs1Lk2FBeMf0SS+OO7xIsBXGMGUiEL9ojS0xRnc4zzgZnVgkrmW2V8YCR8ajK+Nj0wQSFIKXwTl6JOlnwzVdCJXNcmMpiXG2WEftRNGSASIv5h997x3MMGd5/b4oq3A7TZpgSx5zj6XZpjk2FyJL7hZ4vRzUJyGe7QxOFSSh6KBo9m9p11DxUu2g4gWaNhgGBzDmu3tCUIYjiuJrlrFx6qKP8TaUBkTtfLcC53udw=
conda_forge_output_validation: true
